import type { ProductCardItem } from "@/types/product.type";

export type CategoryInfo = {
  slug: string;
  name: string;
  description: string;
};

export const categoryInfoMap: Record<string, CategoryInfo> = {
  iphone: {
    slug: "iphone",
    name: "iPhone",
    description: "Khám phá các dòng iPhone chính hãng, giá tốt, nhiều ưu đãi.",
  },
  ipad: {
    slug: "ipad",
    name: "iPad",
    description: "Các mẫu iPad mạnh mẽ, mỏng nhẹ, phù hợp học tập và làm việc.",
  },
  macbook: {
    slug: "macbook",
    name: "MacBook",
    description: "MacBook chính hãng với hiệu năng mạnh mẽ, thiết kế cao cấp.",
  },
  "apple-watch": {
    slug: "apple-watch",
    name: "Apple Watch",
    description: "Apple Watch theo dõi sức khỏe, luyện tập và kết nối mỗi ngày.",
  },
  "am-thanh": {
    slug: "am-thanh",
    name: "Âm thanh",
    description: "AirPods, tai nghe và loa Apple chính hãng.",
  },
  "phu-kien": {
    slug: "phu-kien",
    name: "Phụ kiện",
    description: "Phụ kiện Apple chất lượng, đồng bộ với thiết bị của bạn.",
  },
};

export const mockProducts: ProductCardItem[] = [
  {
    id: 1,
    name: "iPhone 15 Pro Max 256GB",
    slug: "iphone-15-pro-max-256gb",
    image: "/images/products/iphone-15-pro-max.png",
    price: 28990000,
    oldPrice: 33990000,
    discountLabel: "Giảm 15%",
    installment: "Trả góp 0%",
    promotions: ["Tặng ốp lưng", "Giảm thêm khi thanh toán online"],
    categorySlug: "iphone",
    categoryName: "iPhone",
    colors: ["Titan Tự Nhiên", "Titan Xanh", "Titan Đen"],
    capacities: ["256GB", "512GB", "1TB"],
    stockQuantity: 12,
    stockStatus: "in-stock",
    sold: 210,
    createdAt: "2026-05-01",
  },
  {
    id: 2,
    name: "iPhone 15 128GB",
    slug: "iphone-15-128gb",
    image: "/images/products/iphone-15.png",
    price: 18990000,
    oldPrice: 22990000,
    discountLabel: "Giảm 17%",
    installment: "Trả góp 0%",
    promotions: ["Thu cũ đổi mới trợ giá"],
    categorySlug: "iphone",
    categoryName: "iPhone",
    colors: ["Hồng", "Xanh", "Đen"],
    capacities: ["128GB", "256GB"],
    stockQuantity: 20,
    stockStatus: "in-stock",
    sold: 360,
    createdAt: "2026-04-20",
  },
  {
    id: 3,
    name: "iPhone 14 Pro 128GB",
    slug: "iphone-14-pro-128gb",
    image: "/images/products/iphone-14-pro.png",
    price: 21990000,
    oldPrice: 27990000,
    discountLabel: "Giảm 21%",
    installment: "Trả góp 0%",
    promotions: ["Bảo hành chính hãng 12 tháng"],
    categorySlug: "iphone",
    categoryName: "iPhone",
    colors: ["Tím", "Vàng", "Đen"],
    capacities: ["128GB", "256GB"],
    stockQuantity: 5,
    stockStatus: "in-stock",
    sold: 180,
    createdAt: "2026-03-12",
  },
  {
    id: 4,
    name: "iPhone 13 128GB",
    slug: "iphone-13-128gb",
    image: "/images/products/iphone-13.png",
    price: 13990000,
    oldPrice: 17990000,
    discountLabel: "Giảm 22%",
    installment: "Trả góp 0%",
    promotions: ["Giảm thêm cho học sinh, sinh viên"],
    categorySlug: "iphone",
    categoryName: "iPhone",
    colors: ["Trắng", "Đen", "Xanh"],
    capacities: ["128GB"],
    stockQuantity: 0,
    stockStatus: "out-of-stock",
    sold: 520,
    createdAt: "2026-02-02",
  },
  {
    id: 5,
    name: "iPad Air M2 11 inch WiFi 128GB",
    slug: "ipad-air-m2-11-inch-wifi-128gb",
    image: "/images/products/ipad-air-m2.png",
    price: 16990000,
    oldPrice: 18990000,
    discountLabel: "Giảm 11%",
    installment: "Trả góp 0%",
    promotions: ["Tặng gói Apple TV+ dùng thử"],
    categorySlug: "ipad",
    categoryName: "iPad",
    colors: ["Xanh", "Tím", "Xám"],
    capacities: ["128GB", "256GB"],
    stockQuantity: 8,
    stockStatus: "in-stock",
    sold: 90,
    createdAt: "2026-04-10",
  },
  {
    id: 6,
    name: "MacBook Air M3 13 inch 256GB",
    slug: "macbook-air-m3-13-inch-256gb",
    image: "/images/products/macbook-air-m3.png",
    price: 26990000,
    oldPrice: 29990000,
    discountLabel: "Giảm 10%",
    installment: "Trả góp 0%",
    promotions: ["Tặng Office bản quyền 1 năm"],
    categorySlug: "macbook",
    categoryName: "MacBook",
    colors: ["Midnight", "Starlight", "Silver"],
    capacities: ["256GB", "512GB"],
    ramOptions: ["8GB", "16GB"],
    stockQuantity: 10,
    stockStatus: "in-stock",
    sold: 150,
    createdAt: "2026-05-05",
  },
];